### ISSUE TITLE
PostgreSQL 10 でインストールできない

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/ec-cube#2603]
## 概要(Overview)
インストールすると以下のようなエラーが発生する
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
LINE 1: SELECT min_value, increment_by FROM "dtb_plugin_event_handle...
               ^ in /ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT min_valu...')
#1 /ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('SELECT min_valu...')
#2 /ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT min_valu...', Array, Array)
#3 /ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php(292): Doctrine\DBAL\Connection->fetchAll('SELECT mi in /ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 72

Fatal error: Uncaught PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
LINE 1: SELECT min_value, increment_by FROM "dtb_plugin_event_handle...
               ^ in /ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 72

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "dtb_plugin_event_handler_id_seq"':

SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
LINE 1: SELECT min_value, increment_by FROM "dtb_plugin_event_handle...
               ^ in /ec-cube/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 72

Call Stack:
    0.0012     487648   1. {main}() /ec-cube/eccube_install.php:0
    0.6229    9005448   2. initializeDatabase() /ec-cube/eccube_install.php:76
    1.6706   14213256   3. Doctrine\DBAL\Migrations\Migration->migrate() /ec-cube/eccube_install.php:320
    1.6793   14216296   4. Doctrine\DBAL\Migrations\Version->execute() /ec-cube/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:158
```

## 期待する内容(Expect)  or 要望 (Requirement)
PostgreSQL 10 でインストールできる

## 再現手順(Procedure)
eccube_install.phpを実行
```
$ php eccube_install.php pgsql none
```

### 環境 (environment)
+ EC-CUBE: master
+ PHP: 7.1.10
+ DB:
  - PostgreSQL 10.0.0

**Comment by nnanh01s3** [comment]
I have the same problem

> InvalidFieldNameException in AbstractPostgreSQLDriver.php line 72: An exception occurred while executing 'SELECT min_value, increment_by FROM "dtb_plugin_event_handler_id_seq"':
> 
> SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist
> LINE 1: SELECT min_value, increment_by FROM "dtb_plugin_event_handle...

have anybody from EC-Cube help?

**Comment by kiy0taka** [comment]
Pull requests welcome :)

**Comment by nnanh01s3** [comment]
I found the problem, somewhere in manual document, EC-CUBE said that they don't support PostgreSQL10, so juts reinstall PostgreSQL, all will be fine

**Comment by nanasess** [comment]
Issues to the Doctrine DBAL https://github.com/doctrine/dbal/issues/2868

**Comment by t-nagahashi** [comment]
3.0系マイナーバージョンでは対応が難しいため、
3.nで対応を検討いたします。

**Comment by okazy** [comment]
対応済
