### ISSUE TITLE
Deploy to Herokuでエラー

### ISSUE THREAD

**Issue by yokochi** [EC-CUBE/ec-cube#2852]
## 概要(Overview)
Deploy to Herokuボタンでherokuにdeploy中にエラーになる
以下エラー
```
-----> PHP app detected
-----> Bootstrapping...
-----> Installing platform packages...
       - php (7.2.2)
       - ext-mbstring (bundled with php)
       - apache (2.4.29)
       - nginx (1.8.1)
-----> Installing dependencies...
       Composer version 1.6.3 2018-01-31 16:28:17
       Loading composer repositories with package information
       Installing dependencies from lock file
       Package operations: 61 installs, 0 updates, 0 removals
         - Installing composer/ca-bundle (1.1.0): Downloading (100%)
..省略
       Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
       Generating optimized autoload files
-----> Running 'composer compile'...
       > php eccube_install.php pgsql none --skip-createdb -V
...省略
       update permissions...
       /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/html/template 0700 to 0766
...省略
       Dropping database schema...
       Creating database schema...
       Database schema created successfully!
       
       Fatal error: Uncaught PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
       LINE 1: SELECT min_value, increment_by FROM "dtb_plugin_event_handle...
                      ^ in /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
       Stack trace:
       #0 /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT min_valu...')
       #1 /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('SELECT min_valu...')
       #2 /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT min_valu...', Array, Array)
       #3 /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/D in /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 72
       PHP Fatal error:  Uncaught PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
       LINE 1: SELECT min_value, increment_by FROM "dtb_plugin_event_handle...
                      ^ in /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
       Stack trace:
       #0 /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT min_valu...')
       #1 /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('SELECT min_valu...')
       #2 /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT min_valu...', Array, Array)
       #3 /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/D in /tmp/build_44c4362059ed7685e283147b2ebe2083/EC-CUBE-ec-cube-b6af624/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 72
       Script php eccube_install.php pgsql none --skip-createdb -V handling the compile event returned with error code 255
 !     Push rejected, failed to compile PHP app.
 !     Push failed
 ```

## 期待する内容(Expect)  or 要望 (Requirement)
Deploy to Herokuで正常にdeployされる

## 再現手順(Procedure)
READMEのDeploy to Herokuボタンを押下

### 環境 (environment)
+ EC-CUBE: 3.0.15
+ PHP: 7.2.2
+ DB:
  - PostgreSQL 10.2

## 関連情報 (Ref)
#2603

**Comment by chihiro-adachi** [comment]
#2854 で修正
