### ISSUE TITLE
composer install --no-devでエラー

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#3602]
## 概要(Overview)

```
git clone https://github.com/EC-CUBE/ec-cube.git
cd ec-cube
git checkout origin/4.0
composer install --no-dev

Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear --no-warmup [KO]
 [KO]
Script cache:clear --no-warmup returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebServerBundle" from namespace "Symfony\Bundle\WebServerBundle".
!!  Did you forget a "use" statement for another namespace? in /Users/chihiro_adachi/tmp/ec-cube/src/Eccube/Kernel.php:71
!!  Stack trace:
!!  #0 /Users/chihiro_adachi/tmp/ec-cube/vendor/symfony/http-kernel/Kernel.php(492): Eccube\Kernel->registerBundles()
!!  #1 /Users/chihiro_adachi/tmp/ec-cube/vendor/symfony/http-kernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /Users/chihiro_adachi/tmp/ec-cube/src/Eccube/Kernel.php(86): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /Users/chihiro_adachi/tmp/ec-cube/vendor/symfony/framework-bundle/Console/Application.php(64): Eccube\Kernel->boot()
!!  #4 /Users/chihiro_adachi/tmp/ec-cube/vendor/symfony/console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #5 /User in /Users/chihiro_adachi/tmp/ec-cube/src/Eccube/Kernel.php on line 71
```

挙動としては、
- composer install の時点で, .env.distから.envにファイルがコピーされる
- .env.distはAPP_ENV=devで定義されている
- そのため、app/config/ec-cube/bundles.phpでWebServerBundleを読み込もうとする
- --no-devでcomposer installしているため、WebServerBundleが見つからず上記のエラーが発生する

という流れ

### 環境 (environment)
+ EC-CUBE: 4.0-beta
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by ryo-endo** [comment]
#3666 にて修正完了しております。
