### ISSUE TITLE
Dockerを使用してインストールしようとするとエラーになる

### ISSUE THREAD

**Issue by kazuyoshikakihara** [EC-CUBE/ec-cube#4606]
## 概要(Overview)

開発者向けインストールの「3.Dockerを使用してインストールする」の手順を試したところ docker build の途中でエラーが出て停止しました。

```
Step 20/21 : RUN if [ ! -f ${APACHE_DOCUMENT_ROOT}/var/eccube.db ] && [ ! ${SKIP_INSTALL_SCRIPT_ON_DOCKER_BUILD} = "true" ]; then         composer run-script installer-scripts && composer run-script auto-scripts         ; fi
 ---> Running in 2cfeb2ac415b
> bin/console doctrine:database:create
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "EasyLogHandler" from namespace "EasyCorp\EasyLog".
Did you forget a "use" statement for another namespace? in /var/www/html/var/cache/dev/ContainerXtaarlv/EccubeDevDebugProjectContainer.php:3954
Stack trace:
#0 /var/www/html/var/cache/dev/ContainerXtaarlv/EccubeDevDebugProjectContainer.php(4127): ContainerXtaarlv\EccubeDevDebugProjectContainer->getMonolog_Handler_BufferedService()
#1 /var/www/html/var/cache/dev/ContainerXtaarlv/EccubeDevDebugProjectContainer.php(2729): ContainerXtaarlv\EccubeDevDebugProjectContainer->getMonolog_Logger_TranslationService()
#2 /var/www/html/var/cache/dev/ContainerXtaarlv/EccubeDevDebugProjectContainer.php(4580): ContainerXtaarlv\EccubeDevDebugProjectContainer->getTranslatorService()
#3 /var/www/html/var/cache/dev/ContainerXtaarlv/getValidator_Mapping_CacheWarmerService.php(12): ContainerXtaarlv\EccubeDevDebugProjectContainer->getValidator_BuilderService()
#4 /var/www/html/var/cache/dev/C in /var/www/html/var/cache/dev/ContainerXtaarlv/EccubeDevDebugProjectContainer.php on line 3954
Script bin/console doctrine:database:create handling the installer-scripts event returned with error code 255
The command '/bin/sh -c if [ ! -f ${APACHE_DOCUMENT_ROOT}/var/eccube.db ] && [ ! ${SKIP_INSTALL_SCRIPT_ON_DOCKER_BUILD} = "true" ]; then         composer run-script installer-scripts && composer run-script auto-scripts         ; fi' returned a non-zero code: 255
```

おそらくは composer.json において、

```
"easycorp/easy-log-handler": "^1.0"
```

が "require-dev" のセクションに入ってしまっている一方で、Dockerfile内で

```
RUN composer dumpautoload -o --apcu --no-dev
```

と指定されているため、easy-log-handler がインストールされなくなってしまっているのが原因かと思われます。

「composer.json を書きかえて --no-dev でも easy-log-handler がインストールされるようにする」
あるいは
「--no-devならEC-CUBE内からeasy-log-handlerを呼び出さないようにする」
のいずれかの対応をお願いします。

### 環境 (environment)
+ EC-CUBE: 4.0.4

**Comment by nanasess** [comment]
--no-dev にしておいても、プラグインインストール時に --dev の状態で composer API がコールされてしまい、現状は --no-dev にしているメリットが無い状態です。
Dockerfile 内での指定は `composer dumpautoload -o --apcu` で良いと思われます。

**Comment by kazuyoshikakihara** [comment]
@nanasess ご指示に従い以下のようにDockerfileを変更すれば、無事 docker build が通過しコンテナが正常起動できるところまで確認しました。

```
diff --git a/Dockerfile b/Dockerfile
index 3cac807d14..479dcbafb1 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -71,10 +71,10 @@ USER www-data
 RUN composer install \
   --no-scripts \
   --no-autoloader \
-  --no-dev -d ${APACHE_DOCUMENT_ROOT} \
+  -d ${APACHE_DOCUMENT_ROOT} \
   ;

-RUN composer dumpautoload -o --apcu --no-dev
+RUN composer dumpautoload -o --apcu

 RUN if [ ! -f ${APACHE_DOCUMENT_ROOT}/.env ]; then \
         cp -p .env.dist .env \
```

**Comment by chihiro-adachi** [comment]
@kazuyoshikakihara 
ありがとうございます！その修正で問題ないと思います。
良ければPull Requestいただくことはできますか？

**Comment by kazuyoshikakihara** [comment]
作成しました。
よろしくお願いします。

**Comment by chihiro-adachi** [comment]
ありがとうございます！

**Comment by chihiro-adachi** [comment]
#4608 で修正されました。
