### ISSUE TITLE
キャッシュの手動生成機能

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#4831]
## 概要(Overview)
コンテンツ管理→キャッシュ管理からキャッシュを削除できるが、キャッシュ生成は、初回アクセス時に自動生成される。
管理者以外、一般ユーザーのリクエストで生成される場合もあり、アクセスが多いサイトでは多重にキャッシュ生成が起動してしまい、不整合が発生する場合がある。
また、レンタルサーバーなど、リソースの低いサーバーでは、自動生成時にリソース不足に陥る場合がある

## 期待する内容(Expect)  or 要望 (Requirement)

- キャッシュの自動生成をオフにし、手動生成するオプションを追加する
- キャッシュを手動生成している間は、メンテナンスモードにする

## 再現手順(Procedure)

1. コンテンツ管理→キャッシュ管理からキャッシュ削除
2. フロント画面を F5 アタックしてキャッシュ生成を多重起動する

### 環境 (environment)
+ EC-CUBE: 4.0.5
+ PHP: 7.4.5

**Comment by chihiro-adachi** [comment]
@nanasess 
この修正だとキャッシュ生成中の一般ユーザアクセス防止できたりしますでしょうか？
https://github.com/chihiro-adachi/ec-cube/commit/c184530c38c7f6da541b666315a327e354332b8c

**Comment by nanasess** [comment]
@chihiro-adachi 

`watch -n 1 curl -k -L https://example.com` を5個くらい立ちあげて、一般ユーザーからのアクセスをシミュレートしてみましたが、キャッシュ生成し終わる前にメンテナンス画面が解除されてしまうようで、エラーになってしまいますね🤔

```
[Web Server ] Jan 13 09:55:45 |INFO   | SERVER POST (200) /manager/content/cache/enable_maintenance host="127.0.0.1:8004" scheme="https"
[Web Server ] Jan 13 09:55:45 |INFO   | SERVER POST (200) /manager/content/cache/clear_cache
[Web Server ] Jan 13 09:55:45 |ERROR  | SERVER GET  (503) /
[Web Server ] Jan 13 09:55:45 |INFO   | SERVER POST (200) /manager/content/cache/create_cache host="127.0.0.1:8004" scheme="https"
[Web Server ] Jan 13 09:55:46 |INFO   | SERVER POST (200) /manager/content/cache/disable_maintenance
[PHP-FPM    ] [13-Jan-2021 00:55:49 UTC] PHP Fatal error:  Uncaught RuntimeException: Unable to create the Doctrine Proxy directory "/Users/nanasess/git-repos/ec-cube/var/cache/prod/doctrine/orm/Proxies". in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:57
[PHP-FPM    ] Stack trace:
[Web Server ] Jan 13 09:55:49 |INFO   | SERVER GET  (200) / ip="127.0.0.1"
[Web Server ] Jan 13 09:55:49 |INFO   | SERVER GET  (200) /
[PHP-FPM    ] #0 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(52): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/Users/nanasess...')
[PHP-FPM    ] #1 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(686): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/Users/nanasess...')
[Web Server ] Jan 13 09:55:49 |INFO   | SERVER GET  (200) / ip="127.0.0.1"
[PHP-FPM    ] #2 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
[PHP-FPM    ] #3 /Users/nanasess/git-repos/ec-cube/src/Eccube/Kernel.php(110): Symfony\Component\HttpKernel\Kernel->boot()
[PHP-FPM    ] #4 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(195): Eccube\Kernel->boot()
[PHP-FPM    ] #5 /Users/nanasess/git-repos/ec-cube/index.php( in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php on line 57
[PHP-FPM    ] [13-Jan-2021 00:55:49 UTC] PHP Fatal error:  Uncaught RuntimeException: Unable to create the Doctrine Proxy directory "/Users/nanasess/git-repos/ec-cube/var/cache/prod/doctrine/orm/Proxies". in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:57
[PHP-FPM    ] Stack trace:
[PHP-FPM    ] #0 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(52): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/Users/nanasess...')
[PHP-FPM    ] #1 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(686): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/Users/nanasess...')
[PHP-FPM    ] #2 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
[PHP-FPM    ] #3 /Users/nanasess/git-repos/ec-cube/src/Eccube/Kernel.php(110): Symfony\Component\HttpKernel\Kernel->boot()
[PHP-FPM    ] #4 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(195): Eccube\Kernel->boot()
[PHP-FPM    ] #5 /Users/nanasess/git-repos/ec-cube/index.php( in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php on line 57
[PHP-FPM    ] [13-Jan-2021 00:55:49 UTC] PHP Fatal error:  Uncaught RuntimeException: Unable to create the Doctrine Proxy directory "/Users/nanasess/git-repos/ec-cube/var/cache/prod/doctrine/orm/Proxies". in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:57
[PHP-FPM    ] Stack trace:
[PHP-FPM    ] #0 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(52): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/Users/nanasess...')
[PHP-FPM    ] #1 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(686): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/Users/nanasess...')
[PHP-FPM    ] #2 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
[PHP-FPM    ] #3 /Users/nanasess/git-repos/ec-cube/src/Eccube/Kernel.php(110): Symfony\Component\HttpKernel\Kernel->boot()
[PHP-FPM    ] #4 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(195): Eccube\Kernel->boot()
[PHP-FPM    ] #5 /Users/nanasess/git-repos/ec-cube/index.php( in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php on line 57
[PHP-FPM    ] Jan 13 09:55:50 |WARNING| FPM    [pool www] server reached pm.max_children setting (5), consider raising it
```

**Comment by chihiro-adachi** [comment]
@nanasess 
ありがとうございます。
メンテナンスの解除が早いのかな。調整してみます。

**Comment by chihiro-adachi** [comment]
@nanasess 
create_cacheのタイミングでwarmupするようにしてみました。これでどうでしょうか。
https://github.com/EC-CUBE/ec-cube/commit/be0f33e9b087dd221d0a0af8cdb1782a46dda8d5

**Comment by nanasess** [comment]
@chihiro-adachi 

まだエラーになってしまいますね。。。
自動生成が効いてるんですかね

```
[Web Server ] Jan 13 15:52:10 |INFO   | SERVER GET  (200) /
[Web Server ] Jan 13 15:52:10 |INFO   | SERVER POST (200) /manager/content/cache/enable_maintenance host="127.0.0.1:8004" scheme="https"
[Web Server ] Jan 13 15:52:10 |INFO   | SERVER POST (200) /manager/content/cache/clear_cache
[Web Server ] Jan 13 15:52:10 |INFO   | SERVER POST (200) /manager/content/cache/create_cache
[Web Server ] Jan 13 15:52:10 |INFO   | SERVER POST (200) /manager/content/cache/disable_maintenance
[PHP-FPM    ] [13-Jan-2021 06:52:13 UTC] PHP Fatal error:  Uncaught RuntimeException: Unable to create the Doctrine Proxy directory "/Users/nanasess/git-repos/ec-cube/var/cache/prod/doctrine/orm/Proxies". in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:57
[Web Server ] Jan 13 15:52:13 |INFO   | SERVER GET  (200) / ip="127.0.0.1"
[Web Server ] Jan 13 15:52:13 |INFO   | SERVER GET  (200) /
[PHP-FPM    ] Stack trace:
[PHP-FPM    ] #0 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(52): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/Users/nanasess...')
[PHP-FPM    ] #1 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(686): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/Users/nanasess...')
[PHP-FPM    ] #2 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
[PHP-FPM    ] #3 /Users/nanasess/git-repos/ec-cube/src/Eccube/Kernel.php(110): Symfony\Component\HttpKernel\Kernel->boot()
[PHP-FPM    ] #4 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(195): Eccube\Kernel->boot()
[PHP-FPM    ] #5 /Users/nanasess/git-repos/ec-cube/index.php( in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php on line 57
[PHP-FPM    ] [13-Jan-2021 06:52:13 UTC] PHP Fatal error:  Uncaught RuntimeException: Unable to create the Doctrine Proxy directory "/Users/nanasess/git-repos/ec-cube/var/cache/prod/doctrine/orm/Proxies". in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:57
[PHP-FPM    ] Stack trace:
[PHP-FPM    ] #0 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(52): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/Users/nanasess...')
[PHP-FPM    ] #1 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(686): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/Users/nanasess...')
[PHP-FPM    ] #2 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
[PHP-FPM    ] #3 /Users/nanasess/git-repos/ec-cube/src/Eccube/Kernel.php(110): Symfony\Component\HttpKernel\Kernel->boot()
[PHP-FPM    ] #4 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(195): Eccube\Kernel->boot()
[PHP-FPM    ] #5 /Users/nanasess/git-repos/ec-cube/index.php( in /Users/nanasess/git-repos/ec-cube/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php on line 57
[Web Server ] Jan 13 15:52:14 |ERROR  | SERVER GET  (500) / ip="127.0.0.1"
[PHP-FPM    ] [13-Jan-2021 15:52:14 Asia/Tokyo] PHP Fatal error:  require(): Failed opening required '/Users/nanasess/git-repos/ec-cube/var/cache/prod/doctrine/orm/Proxies/__CG__EccubeEntityMasterDeviceType.php' (include_path='.:/usr/local/Cellar/php@7.4/7.4.13_1/share/php@7.4/pear') in /Users/nanasess/git-repos/ec-cube/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 206
[Web Server ] Jan 13 15:52:14 |INFO   | SERVER GET  (200) / ip="127.0.0.1"
[Web Server ] Jan 13 15:52:14 |INFO   | SERVER GET  (200) /
[
```

**Comment by chihiro-adachi** [comment]
@nanasess 
ありがとうございます。
うーんなんでだろう。
環境はSymfonyのFPMサーバですか？

**Comment by nanasess** [comment]
@chihiro-adachi はい、 symfony/cli + php-fpm です。
もしかして、Apache + mod_php なら問題ない？

**Comment by chihiro-adachi** [comment]
@nanasess 
こちらのDocker使って試していますが、特にシステムエラーは発生しないです。
https://github.com/EC-CUBE/ec-cube/blob/4.0/Dockerfile

**Comment by nanasess** [comment]
@chihiro-adachi Docker で試してみました。 Apache + mod_php は問題なさそうですね

**Comment by chihiro-adachi** [comment]
@nanasess 
ありがとうございます。
apache + mod_phpで効果あるなら、いったんこの修正をキャッシュ削除してるところに組み込んでもよいかもしれないなあと思いました。

根治ではないですが低減はできそうな印象。

**Comment by nanasess** [comment]
@chihiro-adachi いいと思います。ただ、php-fpm を採用するケースも多くなっていると思いますので、画面から手動で warmup する機能もあるといいかなと思います
