### ISSUE TITLE
[4.2] カート画面からレジに進む際のエラー

### ISSUE THREAD

**Issue by fujisaki55** [EC-CUBE/ec-cube#5451]
## 概要(Overview)
カートに商品を追加し、カート画面からレジに進むをクリックする
　→システムエラーが表示された 
 [2022-07-13T08:03:22.143456+09:00] front.ERROR [8c361c8e] [e18dadf] [N/A] [Eccube\Log\Logger:log:66] - システムエラーが発生しました。 ["The controller for URI \"/shopping\" is not callable: The \"\" mailer DSN must contain a scheme.","/var/www/html/ec-cube/support001/vendor/symfony/http-kernel/Controller/ControllerResolver.php",88,"#0 /var/www/html/ec-cube/support001/vendor/symfony/http-kernel/HttpKernel.php(135): Symfony\\Component\\HttpKernel\\Controller\\ControllerResolver->getController()\n#1 /var/www/html/ec-cube/support001/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#2 /var/www/html/ec-cube/support001/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#3 /var/www/html/ec-cube/support001/index.php(83): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#4 {main}"] [GET, /ec-cube/support001/shopping, 111.216.12.50, http://153.125.239.224/ec-cube/support001/shopping, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36]

## 再現手順(Procedure)
カートに商品を追加し、カート画面からレジに進むをクリックする

### 環境 (environment)
EC-CUBE: 4.2.0-beta
PHP: ？
DB: ？
PostgreSQL x.x.x
MySQL x.x.x

## 関連情報 (Ref)
バグバウンティExcel#1

**Comment by chihiro-adachi** [comment]
通常のインストールでは発生しないが、`MAILER_DSN`が未定義の場合、注文画面や会員登録画面でシステムエラーとなる。
4.0/4.1と同様デフォルト値を定義しておくのがよいかと思われる。

**Comment by chihiro-adachi** [comment]
#5468 で対応
