### ISSUE TITLE
[4.2]  PHP8とMySQLでプラグインの削除やアップデート時にシステムエラー

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5455]
## 概要(Overview)

プラグインの削除やアップデート時にシステムエラー(There is no active transaction)が発生する。
PHP8.0/8.1とMySQLの組み合わせで発生し、PHP7.4では発生しない。

```
[2022-07-21T08:08:49.602866+09:00] app.DEBUG [N/A] [340258a] [1] [Eccube\EventListener\LogListener:onKernelTerminate:133] - PROCESS END ["admin_store_plugin_api_uninstall"] [DELETE, /admin2/store/plugin/api/delete/1/uninstall, 127.0.0.1, http://127.0.0.1:8000/admin2/store/plugin, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36]
[2022-07-21T08:08:49.603303+09:00] php.CRITICAL [N/A] [340258a] [1] [Symfony\Component\ErrorHandler\ErrorHandler:handleException:584] - Uncaught Exception: There is no active transaction {"exception":"[object] (PDOException(code: 0): There is no active transaction at /Users/chihiro_adachi/repos/ec-cube42/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:118)"} [DELETE, /admin2/store/plugin/api/delete/1/uninstall, 127.0.0.1, http://127.0.0.1:8000/admin2/store/plugin, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36]

[2022-07-21T08:08:49.606408+09:00] app.ERROR [N/A] [340258a] [1] [Eccube\Log\Logger:log:68] - システムエラーが発生しました。 ["There is no active transaction","/Users/chihiro_adachi/repos/ec-cube42/vendor/doctrine/dbal/src/Driver/PDO/Connection.php",118,"#0 /Users/chihiro_adachi/repos/ec-cube42/vendor/doctrine/dbal/src/Driver/PDO/Connection.php(118): PDO->commit()\n#1 /Users/chihiro_adachi/repos/ec-cube42/vendor/doctrine/dbal/src/Connection.php(1347): Doctrine\\DBAL\\Driver\\PDO\\Connection->commit()\n#2 /Users/chihiro_adachi/repos/ec-cube42/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(280): Doctrine\\DBAL\\Connection->commit()\n#3 /Users/chihiro_adachi/repos/ec-cube42/var/cache/prod/ContainerWHLcZyE/EntityManager_9a5be93.php(53): Doctrine\\ORM\\EntityManager->commit()\n#4 /Users/chihiro_adachi/repos/ec-cube42/src/Eccube/EventListener/TransactionListener.php(131): ContainerWHLcZyE\\EntityManager_9a5be93->commit()\n#5 /Users/chihiro_adachi/repos/ec-cube42/vendor/symfony/event-dispatcher/EventDispatcher.php(270): Eccube\\EventListener\\TransactionListener->onKernelTerminate()\n#6 /Users/chihiro_adachi/repos/ec-cube42/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}()\n#7 /Users/chihiro_adachi/repos/ec-cube42/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()\n#8 /Users/chihiro_adachi/repos/ec-cube42/vendor/symfony/http-kernel/HttpKernel.php(94): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n#9 /Users/chihiro_adachi/repos/ec-cube42/vendor/symfony/http-kernel/Kernel.php(159): Symfony\\Component\\HttpKernel\\HttpKernel->terminate()\n#10 /Users/chihiro_adachi/repos/ec-cube42/index.php(85): Symfony\\Component\\HttpKernel\\Kernel->terminate()\n#11 {main}"] [DELETE, /admin2/store/plugin/api/delete/1/uninstall, 127.0.0.1, http://127.0.0.1:8000/admin2/store/plugin, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36]
[2022-07-21T08:08:49.609872+09:00] app.DEBUG [N/A] [340258a] [1] [Eccube\EventListener\LogListener:onKernelResponse:124] - LOGIC END ["admin_store_plugin_api_uninstall"] [DELETE, /admin2/store/plugin/api/delete/1/uninstall, 127.0.0.1, http://127.0.0.1:8000/admin2/store/plugin, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36]
```

## 期待する内容(Expect)  or 要望 (Requirement)

- 正常に削除できること

## 再現手順(Procedure)

- メールマガジンプラグインをインストール
- 有効化
- 無効化
- 削除
   - 削除実行後、モーダルの表示が切り替わらず、応答が帰ってこないように見える
   - ログ上ではThere is no active transactionのシステムエラーが発生している

### 環境 (environment)
+ EC-CUBE: 4.2.0のHEAD
+ PHP: 8.0, 8.1
+ DB:
  - MySQL 5.7, 8.0

## 関連情報 (Ref)

#5443

**Comment by chihiro-adachi** [comment]
#5443 で対応
