### ISSUE TITLE
CSVを出力するとシステムエラーになる

### ISSUE THREAD

**Issue by ghost** [EC-CUBE/ec-cube#5754]
## 概要(Overview)
EC-CUBEインストール初期状態のCSV出力機能でシステムエラーが発生する。

## 再現手順(Procedure)
商品一覧画面の「CSVダウンロード」ボタンを押す。
出力されたCSVの中身を見るとエラー画面のHTMLが書き込まれている。
※他のCSV出力でも同様

### 環境 (environment)
+ さくらのレンタルサーバー
+ EC-CUBE: 4.2.0-beta2
+ PHP: 7.4.30
+ DB:
  - MySQL 5.7.37

## 関連情報 (Ref)
エラーログ内容
```
[Eccube\Log\Logger:log:64] - システムエラーが発生しました。 ["Failed to start the session because headers have already been sent by \"/home/test/www/eccube-4.2.0-beta2/src/Eccube/Service/CsvExportService.php\" at line 387.","/home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php",145,"#0 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(352): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->start()\n#1 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Session.php(261): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->getBag('attributes')\n#2 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Session.php(283): Symfony\\Component\\HttpFoundation\\Session\\Session->getBag('attributes')\n#3 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Session.php(77): Symfony\\Component\\HttpFoundation\\Session\\Session->getAttributeBag()\n#4 /home/test/www/eccube-4.2.0-beta2/src/Eccube/Service/CsvExportService.php(460): Symfony\\Component\\HttpFoundation\\Session\\Session->get('eccube.admin.pr...', Array)\n#5 /home/test/www/eccube-4.2.0-beta2/src/Eccube/Controller/Admin/Product/ProductController.php(972): Eccube\\Service\\CsvExportService->getProductQueryBuilder(Object(Symfony\\Component\\HttpFoundation\\Request))\n#6 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/StreamedResponse.php(109): Eccube\\Controller\\Admin\\Product\\ProductController->Eccube\\Controller\\Admin\\Product\\{closure}()\n#7 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Response.php(394): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()\n#8 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/EventListener/StreamedResponseListener.php(41): Symfony\\Component\\HttpFoundation\\Response->send()\n#9 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/EventDispatcher.php(270): Symfony\\Component\\HttpKernel\\EventListener\\StreamedResponseListener->onKernelResponse(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#10 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#11 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'kernel.response', Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent))\n#12 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/HttpKernel.php(186): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response')\n#13 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/HttpKernel.php(174): Symfony\\Component\\HttpKernel\\HttpKernel->filterResponse(Object(Symfony\\Component\\HttpFoundation\\StreamedResponse), Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#14 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#15 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#16 /home/test/www/eccube-4.2.0-beta2/index.php(83): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#17 {main}"]
```

**Comment by nanasess** [comment]
何らかの原因で、セッションが正常に開始されていないようです。
環境変数(.env)を以下のように設定して、どうなるか試していただくことは可能でしょうか？
```
APP_ENV=dev
APP_DEBUG=1
```

**Comment by chihiro-adachi** [comment]
手元の環境では再現しませんでした。

EC-CUBE: 4.2.0-beta2-20220829をコマンドラインからインストール
PHP: 7.4.27
DB:PostgreSQL 10

APP_ENV: prod / dev いずれも再現せず

**Comment by chihiro-adachi** [comment]
@sw-shigeyoshi-koyama 
上記ご確認お願いいたします。

**Comment by ghost** [comment]
```
APP_ENV=dev
APP_DEBUG=1
```
環境変数を上記に変更してキャッシュクリア後にそれぞれ試しました。
- 商品一覧 > CSVダウンロードを実行
- ChromeでCookieを削除してから管理画面へ再ログイン。もう一度CSVダウンロード

結果：どちらも挙動は変わらず出力されたファイルに同様のエラーが書き込まれました。


``` 
/var/log/dev/site.logより抜粋

___ *** CRITICAL ERROR *** ==> REQUEST _____________________________________________________________
Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already
  been sent by "/home/test/www/eccube-4.2.0-beta2/src/Eccube/Service/CsvExportService.php" at
  line 387." at
  /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php
  line 145
--> exception:
      class: RuntimeException
      message: 'Failed to start the session because headers have already been sent by "/home/test/www/eccube-4.2.0-beta2/src/Eccube/Service/CsvExportService.php" at line 387.'
      code: 0
      file: /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php
      line: 145
      trace: "#0 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(352): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->start()\n#1 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Session.php(261): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->getBag('attributes')\n#2 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Session.php(283): Symfony\\Component\\HttpFoundation\\Session\\Session->getBag('attributes')\n#3 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/Session.php(77): Symfony\\Component\\HttpFoundation\\Session\\Session->getAttributeBag()\n#4 /home/test/www/eccube-4.2.0-beta2/src/Eccube/Service/CsvExportService.php(460): Symfony\\Component\\HttpFoundation\\Session\\Session->get('eccube.admin.pr...', Array)\n#5 /home/test/www/eccube-4.2.0-beta2/src/Eccube/Controller/Admin/Product/ProductController.php(972): Eccube\\Service\\CsvExportService->getProductQueryBuilder(Object(Symfony\\Component\\HttpFoundation\\Request))\n#6 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/StreamedResponse.php(109): Eccube\\Controller\\Admin\\Product\\ProductController->Eccube\\Controller\\Admin\\Product\\{closure}()\n#7 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Response.php(394): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()\n#8 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/EventListener/StreamedResponseListener.php(41): Symfony\\Component\\HttpFoundation\\Response->send()\n#9 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(117): Symfony\\Component\\HttpKernel\\EventListener\\StreamedResponseListener->onKernelResponse(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#10 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#11 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'kernel.response', Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent))\n#12 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(154): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response')\n#13 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/HttpKernel.php(186): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response')\n#14 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/HttpKernel.php(174): Symfony\\Component\\HttpKernel\\HttpKernel->filterResponse(Object(Symfony\\Component\\HttpFoundation\\StreamedResponse), Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#15 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#16 /home/test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#17 /home/test/www/eccube-4.2.0-beta2/index.php(83): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#18 {main}"
      previous: null
```


補足になるのですが、Dockerでのローカル環境構築時にこのエラーは発生せず
この商用環境だと各種バージョンのコマンドラインインストールやパッケージ版でのWebインストールなども試しましたが全てエラーになっているような感じです。私の何かしら操作ミスでしたら申し訳ないのですが...。

**Comment by nanasess** [comment]
@sw-shigeyoshi-koyama 
https://github.com/EC-CUBE/ec-cube/releases/tag/4.2.0-beta2-20220905 をさくらのレンタルサーバー(スタンダードプラン)にインストールしてみましたが、正常に CSV ダウンロードできました。
何日のバージョンの beta2 をお使いでしたでしょうか？

**Comment by ghost** [comment]
@nanasess 
https://github.com/EC-CUBE/ec-cube/releases/tag/4.2.0-beta2-20220829
https://github.com/EC-CUBE/ec-cube/releases/tag/4.2.0-beta2-20220826
https://github.com/EC-CUBE/ec-cube/releases/tag/4.2.0-beta2
このバージョンで試しました。

https://github.com/EC-CUBE/ec-cube/releases/tag/4.2.0-beta2-20220905 のバージョンで動作するかこちらでも確認してみます。情報ありがとうございます。

**Comment by nanasess** [comment]
@sw-shigeyoshi-koyama phpinfo() の情報をいただけますでしょうか。PHPがCGIモードで動作してませんでしょうか？

**Comment by ghost** [comment]
@nanasess phpinfoで確認したところモジュールモードになっています。

![image](https://user-images.githubusercontent.com/80671439/188789358-c7bd7545-6a94-45ee-b151-22f3cc9b52a7.png)
![image](https://user-images.githubusercontent.com/80671439/188789414-351aa393-203a-444b-baa7-1755ecb2fc4e.png)
![image](https://user-images.githubusercontent.com/80671439/188789420-ca148e27-7565-4eda-81ee-53af90bb39bb.png)

**Comment by nanasess** [comment]
@sw-shigeyoshi-koyama ありがとうございます。 phpinfo() の session の項目を見せていただけますでしょうか。
また、 php.ini の設定は何か変更されていませんでしょうか？

**Comment by ghost** [comment]
@nanasess 
sessionの項目です。
※4.1.2はこれと同じ設定で正常にcsv出力されました。
![image](https://user-images.githubusercontent.com/80671439/189016677-8aff2dd5-1e70-45dc-a536-e74e6f301ac5.png)

php.ini(一部意味のない項目もあり)
```
memory_limit = 512M
max_execution_time = 180
date.timezone = Asia/Tokyo
extension = sodium
extension = apcu
extension = mcrypt
extension = opcache
```

**Comment by nanasess** [comment]
@sw-shigeyoshi-koyama php.ini の設定は問題なさそうですね。
以下の修正を元に戻してみるとどうなりますでしょうか？
https://github.com/EC-CUBE/ec-cube/commit/1ff28cc7a30ee7ab98b78957d08c6474fd452b46

**Comment by ghost** [comment]
@nanasess 
修正箇所を元に戻して動作確認しました。
相変わらず同じ個所でエラーが発生しますが、例外が発生する場所が変わりますね。

```
/var/log/dev/site.logより抜粋

___ *** CRITICAL ERROR *** ==> REQUEST _____________________________________________________________
Uncaught PHP Exception ErrorException: "Warning: Cannot modify header information - headers
  already sent by (output started at
  /home/sw-test/www/eccube-4.2.0-beta2/src/Eccube/Service/CsvExportService.php:387)" at
  /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/SessionUtils.php line
  52
--> exception:
      class: ErrorException
      message: 'Warning: Cannot modify header information - headers already sent by (output started at /home/sw-test/www/eccube-4.2.0-beta2/src/Eccube/Service/CsvExportService.php:387)'
      code: 0
      file: /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/http-foundation/Session/SessionUtils.php
      line: 52
      trace: "#0 /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/EventListener/AbstractSessionListener.php(153): Symfony\\Component\\HttpFoundation\\Session\\SessionUtils::popSessionCookie('eccube', '6e6ee0c76c42679...')\n#1 /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(117): Symfony\\Component\\HttpKernel\\EventListener\\AbstractSessionListener->onKernelResponse(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#2 /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#3 /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'kernel.response', Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent))\n#4 /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(154): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response')\n#5 /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/HttpKernel.php(186): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), 'kernel.response')\n#6 /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/HttpKernel.php(174): Symfony\\Component\\HttpKernel\\HttpKernel->filterResponse(Object(Symfony\\Component\\HttpFoundation\\StreamedResponse), Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#7 /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#8 /home/sw-test/www/eccube-4.2.0-beta2/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#9 /home/sw-test/www/eccube-4.2.0-beta2/index.php(83): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#10 {main}"
      previous: null
```

**Comment by nanasess** [comment]
@sw-shigeyoshi-koyama いろいろ調べてみましたが再現性が無く、ご利用の環境固有の問題かもしれません。
もし可能であれば、さくらのレンタルサーバーにお試しで申し込んでいただき、別のアカウントで試していただくことは可能でしょうか？

**Comment by nanasess** [comment]
@sw-shigeyoshi-koyama  mcrypt extension は PHP7.2 以降削除されています。
phpinfo() の情報をみると、 mcrypt.ini が読み込まれているようです。
こちらを削除してみていただくことは可能でしょうか？

**Comment by chihiro-adachi** [comment]
@sw-satoshi-nakano 
環境によっては発生するようです。
以下と同様の修正をいれると解消されましたがいかがでしょうか。
https://github.com/EC-CUBE/ProductReview-plugin/pull/81/files

**Comment by chihiro-adachi** [comment]
再現を確認できましたので、https://github.com/EC-CUBE/ec-cube/pull/5892 で修正しています。
検索条件構築時にセッションにアクセスしており、その際に `session already been sent`のエラーが発生していたようです。
