### ISSUE TITLE
プラグインを削除するとスロットリングが機能しなくなる

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#5957]
### 概要(Overview)

プラグインを削除するとスロットリング用のテーブルが削除されます。
その結果、会員登録や購入フローなどスロットリングが実行される箇所でシステムエラーが発生します。

```
システムエラーが発生しました。 ["An exception occurred while executing a query: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block","/Users/chihiro_adachi/tmp/ec-cube/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php",87,"#0 /Users/chihiro_adachi/tmp/ec-cube/vendor/doctrine/dbal/src/Connection.php(1907): Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter->convert()\n#1 /Users/chihiro_adachi/tmp/ec-cube/vendor/doctrine/dbal/src/Connection.php(1850): Doctrine\\DBAL\\Connection->handleDriverException()\n#2 /Users/chihiro_adachi/tmp/ec-cube/vendor/doctrine/dbal/src/Connection.php(1069): Doctrine\\DBAL\\Connection->convertExceptionDuringQuery()\n#3 /Users/chihiro_adachi/tmp/ec-cube/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(750): Doctrine\\DBAL\\Connection->executeQuery()\n#4 /Users/chihiro_adachi/tmp/ec-cube/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(241): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->load()\n#5 /Users/chihiro_adachi/tmp/ec-cube/src/Eccube/Repository/CustomerRepository.php(391): Doctrine\\ORM\\EntityRepository->findOneBy()\n#6 /Users/chihiro_adachi/tmp/ec-cube/src/Eccube/Controller/ForgotController.php(101): Eccube\\Repository\\CustomerRepository->getRegularCustomerByEmail()\n#7 /Users/chihiro_adachi/tmp/ec-cube/vendor/symfony/http-kernel/HttpKernel.php(163): Eccube\\Controller\\ForgotController->index()\n#8 /Users/chihiro_adachi/tmp/ec-cube/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#9 /Users/chihiro_adachi/tmp/ec-cube/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#10 /Users/chihiro_adachi/tmp/ec-cube/index.php(83): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#
```

### 原因

以下の箇所でテーブルの削除が行われるが、ShcemaTool自体に拡張機構がある。
https://github.com/EC-CUBE/ec-cube/blob/4.2/src/Eccube/Service/SchemaService.php#L146

ShcemaTool::getSchemaFromMetadata()が呼ばれた際に、`DoctrineDbalAdapter`で追加されたcache_itemsが削除対象として追加されてしまう模様。

### 再現手順(Procedure)

- 4.2.1環境をセットアップする
- 管理画面＞オーナーズストア＞プラグイン一覧から、任意のプラグインを削除する
- cache_itemsテーブルが削除されている

### 環境(Environment)

EC-CUBE 4.2.1

### 関連

https://github.com/EC-CUBE/ec-cube/pull/5881

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/pull/5958 で対応
