### ISSUE TITLE
4.2.1 オーナーズストア経由のプラグインインストール>有効化でエラー発生

### ISSUE THREAD

**Issue by KenTanaka** [EC-CUBE/ec-cube#5965]
### 概要(Overview)

EC-CUBE4.2.1 オーナーズストア経由のプラグインインストール＞有効化時に
いくつかのプラグインで有効化後に「システムエラーが発生しました。」画面が表示される。
（その後、管理画面URLへアクセスしても「システムエラーが発生しました。」が維持される。）

発生パターンは現段階では不明。
環境組み合わせとの因果関係も不明。

事象発生後、bin/console cache:clear でキャッシクリアした後は管理画面へログイン可能となった。

直近発生時は、以下のログがsite-logに出力されています。
発生状況は
　MYSQL環境 > 発生せず
　PGSQL環境 > 発生
但し、別プラグインでは、MYSQL / PGSQLともに発生しており、一様ではない模様。

■プラグイン有効化ボタン押下後

```
[2023-03-08T12:45:08.463509+09:00] admin.ERROR [aa357e9a] [9010b40] [N/A] [Eccube\Log\Logger:log:64] - システムエラーが発生しました。 ["Failed opening required '/var/www/html/ec-cube/p/var/cache/prod/doctrine/orm/Proxies/__CG__EccubeEntityMasterWork.php' (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php')","/var/www/html/ec-cube/p/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php",197,"#0 /var/www/html/ec-cube/p/vendor/doctrine/common/src/Proxy/AbstractProxyFactory.php(109): Doctrine\\Common\\Proxy\\AbstractProxyFactory->getProxyDefinition()\n#1 /var/www/html/ec-cube/p/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2909): Doctrine\\Common\\Proxy\\AbstractProxyFactory->getProxy()\n#2 /var/www/html/ec-cube/p/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(152): Doctrine\\ORM\\UnitOfWork->createEntity()\n#3 /var/www/html/ec-cube/p/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(63): Doctrine\\ORM\\Internal\\Hydration\\SimpleObjectHydrator->hydrateRowData()\n#4 /var/www/html/ec-cube/p/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(270): Doctrine\\ORM\\Internal\\Hydration\\SimpleObjectHydrator->hydrateAllData()\n#5 /var/www/html/ec-cube/p/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(758): Doctrine\\ORM\\Internal\\Hydration\\AbstractHydrator->hydrateAll()\n#6 /var/www/html/ec-cube/p/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(241): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->load()\n#7 /var/www/html/ec-cube/p/src/Eccube/Security/Core/User/MemberProvider.php(45): Doctrine\\ORM\\EntityRepository->findOneBy()\n#8 /var/www/html/ec-cube/p/src/Eccube/Security/Core/User/MemberProvider.php(72): Eccube\\Security\\Core\\User\\MemberProvider->loadUserByUsername()\n#9 /var/www/html/ec-cube/p/vendor/symfony/security-http/Firewall/ContextListener.php(236): Eccube\\Security\\Core\\User\\MemberProvider->refreshUser()\n#10 /var/www/html/ec-cube/p/vendor/symfony/security-http/Firewall/ContextListener.php(137): Symfony\\Component\\Security\\Http\\Firewall\\ContextListener->refreshUser()\n#11 /var/www/html/ec-cube/p/vendor/symfony/security-http/Firewall/AbstractListener.php(26): Symfony\\Component\\Security\\Http\\Firewall\\ContextListener->authenticate()\n#12 /var/www/html/ec-cube/p/vendor/symfony/security-http/Firewall.php(119): Symfony\\Component\\Security\\Http\\Firewall\\AbstractListener->__invoke()\n#13 /var/www/html/ec-cube/p/vendor/symfony/security-http/Firewall.php(92): Symfony\\Component\\Security\\Http\\Firewall->callListeners()\n#14 /var/www/html/ec-cube/p/vendor/symfony/event-dispatcher/EventDispatcher.php(270): Symfony\\Component\\Security\\Http\\Firewall->onKernelRequest()\n#15 /var/www/html/ec-cube/p/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}()\n#16 /var/www/html/ec-cube/p/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()\n#17 /var/www/html/ec-cube/p/vendor/symfony/http-kernel/HttpKernel.php(139): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n#18 /var/www/html/ec-cube/p/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#19 /var/www/html/ec-cube/p/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#20 /var/www/html/ec-cube/p/index.php(83): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#21 {main}"] [GET, /p/test/store/plugin, 133.106.255.43, https://example.ec-cube.net/p/test/store/plugin, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36]


[2023-03-08T12:45:29.804114+09:00] admin.ERROR [063de329] [2f559a5] [1] [Eccube\Log\Logger:log:64] - システムエラーが発生しました。 ["Unable to generate a URL for the named route \"admin_shipping__csv_import\" as such route does not exist.","/var/www/html/ec-cube/p/vendor/symfony/routing/Generator/CompiledUrlGenerator.php",50,"#0 /var/www/html/ec-cube/p/vendor/symfony/routing/Router.php(235): Symfony\\Component\\Routing\\Generator\\CompiledUrlGenerator->generate()\n#1 /var/www/html/ec-cube/p/src/Eccube/EventListener/TwigInitializeListener.php(283): Symfony\\Component\\Routing\\Router->generate()\n#2 /var/www/html/ec-cube/p/src/Eccube/EventListener/TwigInitializeListener.php(274): Eccube\\EventListener\\TwigInitializeListener->getDisplayEccubeNav()\n#3 /var/www/html/ec-cube/p/src/Eccube/EventListener/TwigInitializeListener.php(253): Eccube\\EventListener\\TwigInitializeListener->getDisplayEccubeNav()\n#4 /var/www/html/ec-cube/p/src/Eccube/EventListener/TwigInitializeListener.php(158): Eccube\\EventListener\\TwigInitializeListener->setAdminGlobals()\n#5 /var/www/html/ec-cube/p/vendor/symfony/event-dispatcher/EventDispatcher.php(270): Eccube\\EventListener\\TwigInitializeListener->onKernelRequest()\n#6 /var/www/html/ec-cube/p/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}()\n#7 /var/www/html/ec-cube/p/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()\n#8 /var/www/html/ec-cube/p/vendor/symfony/http-kernel/HttpKernel.php(139): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n#9 /var/www/html/ec-cube/p/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#10 /var/www/html/ec-cube/p/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#11 /var/www/html/ec-cube/p/index.php(83): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#12 {main}"] [GET, /p/test/, 133.106.255.43, https://example.ec-cube.net/p/test/login,

```

### 再現手順(Procedure)

・必ず再現するものではない

### 環境(Environment)

EC-CUBE: 4.2.1
PHP: 8.1.1
DB:
  MYSQL: 8.1
  PGSQ: 14.4

**Comment by nanasess** [comment]
Doctrine ORM のキャッシュ生成時のエラー
https://qiita.com/nanasess/items/791c9ec98f69ada93ea0#doctrine-orm-%E3%81%AE%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5%E7%94%9F%E6%88%90%E6%99%82%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC

またはSymfony DependencyInjection コンテナのコンパイル時のエラー
https://qiita.com/nanasess/items/791c9ec98f69ada93ea0#symfony-dependencyinjection-%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%91%E3%82%A4%E3%83%AB%E6%99%82%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC

だと思われます。
管理画面からの操作が不安定なのは否めず、根本解決は難しいと思われます。
[コマンドラインからの操作](https://qiita.com/nanasess/items/791c9ec98f69ada93ea0#%E5%AF%BE%E5%87%A6%E6%96%B9%E6%B3%95-2) でしたら安定していると思いますがいかがでしょうか。

4.2.1から顕著になったのであれば、[symfony/cacheの変更](https://github.com/symfony/cache/commits/5.4)に起因している可能性があります

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube/issues/5965#issuecomment-1461153072 の指摘どおり、根本解決は難しいことからクローズします。

再現状況等、今後わかるようでしたらReOpenお願いします。
